### ISSUE TITLE
No Compiled Download?

### ISSUE THREAD

**Issue by The-Artificer** [Aurilux/Cybernetica#3]
I have been searching for the 1.7.10 version of Cybernetica in jar form for a good while now, but haven't been able to find it. All links turn up a dead end to a forum post that links to another, which only has a couple downloads for other unrelated projects. Is there somewhere that I can download a compiled .jar of this mod anymore?

**Comment by The-Artificer** [comment]
I have a very strong memory of a cybernetics mod in 1.7.10 highly similar to the current cyberware, and have been trying for the life of me to actually find it anywhere, but can't seem to do so. I'm not sure if this is it, but I think it's possible that it might be.

**Comment by Aurilux** [comment]
Yeah, I think at the time I was using Dropbox to host my downloads. Said account was disabled during my long hiatus between 1.7.10 and 1.12, and since I never really used anyway, never tried to get it back. I began posting my mods to Curseforge during 1.12, but I didn't have the time to update Cybernetica. Honestly, there wasn't much to it in 1.7.10, and right now I'm focused on 1.16.4. Cybernetica is on my list, but it'll be a while as I update my other mods and rework Cybernetica. If you have any more questions or comments about this, feel free to hit me up in my discord: https://discord.gg/hnqA2Wc.
